### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by arhonemus** [NYPL/digarch_scripts#45]
When running report_ftk_extents.py the following error occurred and no JSON was created.
Creating report ...
ER 277: 1998-2012 contains the following 0-byte file: Picture clipping.pictClipping. Review this file with the processing archivist.
ER 278: 2009-2012 contains the following 0-byte file: 16. Review this file with the processing archivist.
ER 278: 2009-2012 contains the following 0-byte file: 20121016-062804. Review this file with the processing archivist.
ER 148: Scores contains the following 0-byte file: LLL Orchestrations. Review this file with the processing archivist.
ER 254: Backup Files, 2011-2017 contains the following 0-byte file: UNKNOWN SOLDIER. Review this file with the processing archivist.
ER 357: Call Gabrielle contains the following 0-byte file: Session File Backups. Review this file with the processing archivist.
Traceback (most recent call last):
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 349, in <module>
    main()
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 343, in main
    dct = create_report(er, dct)
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 285, in create_report
    item = create_report(input, item)
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 289, in create_report
    create_report(input, {'title': parent, 'children': []})
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 289, in create_report
    create_report(input, {'title': parent, 'children': []})
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 289, in create_report
    create_report(input, {'title': parent, 'children': []})
  [Previous line repeated 1 more time]
  File "/mnt/c/Users/foren/Documents/GitHub/digarch_scripts/src/digarch_scripts/report/report_ftk_extents.py", line 272, in create_report
    number, name = input[0].split(':', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by nkrabben** [comment]
The problem is because some ER titles have '/' in the text. We use '/' to create a string of component hierarchy, that trips up L207 which extracts the ER name based on splitting on '/', which trips up L289.

Best solution is to not overload the meaning of '/'. Instead of making a string of hierarchy, I think it would be better to make a list. Then we don't have to find a special character to separate the components in a string.

**Comment by nkrabben** [comment]
I attempted that approach, and it seems to work, although it breaks tests. I'll put some time into updating everything before submitting a PR.
